### ISSUE TITLE
[ToDo] Features

### ISSUE THREAD

**Issue by mosemister** [mosemister/Ships-5-Bukkit-Version#5]
Commands:
- [x] [x] Ships info
- [ ] [ ] Ships info _Ship type_
- [ ] [ ] Ships info _Ship name_
- [ ] [ ] Ships teleport _Ship name_
- [ ] [ ] Ships teleport _Ship name_ _players..._

Algorithms:
- [x] [ ] Ships 6 movement 
- [x] [x] Ships 5 movement
- [ ] [ ] Ships 6 autopilot path finder
- [x] [x] Ships 6 block finder

Features:
- [x] [x] Remove ship on licence break
- [ ] [ ] Logout overboard bug fix
- [ ] [ ] Force name on licence sign config option
- [x] [ ] Structure destroy on unlicence config option
- [ ] [ ] Protected Ships option
- [ ] [ ] Subpilots
- [ ] [ ] ShipsLock
- [x] [x] Ships get stored into temp storage
- [x] [x] Ships are automatic removed from temp storage when not used
- [ ] [ ] Command tab completion for all default ships commands

Ship types:
- [x] [x] Airship
- [ ] [ ] Marsship
- [x] [x] Watership
- [ ] [ ] Submarine
- [ ] [ ] Plane
- [ ] [ ] Solarship
- [ ] [ ] UnnamedShip (the old hybridship)
- [ ] [ ] Hybridship (revisited)

Other plugins:
- [ ] [ ] GriefProtectionHook
- [ ] [ ] WorldGuardHook

Events:
- [x] [x] ShipAboutToMoveEvent
- [x] [x] ShipTransformEvent
- [ ] [ ] ShipTeleportEvent
- [ ] [ ] ShipTransformSectionEvent
- [ ] [ ] ShipTeleportSectionEvent
- [ ] [ ] ShipFallingEvent
- [ ] [ ] AutopilotAttemptMoveEvent
- [x] [ ] ShipTrackedEvent
- [x] [x] ShipCreatedEvent
- [x] [x] ShipLoadEvent
- [x] [x] ShipUnloadEvent

API:
- [ ] [ ] CustomInventoryAPI
